name: Run tests

on: [push]

jobs:
    unit-test:
        runs-on: ubuntu-latest

        steps:
            - name: checkout Code
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
            - name: Run unit tests
              run: yarn test:unit
